# Generated by Django 6.0 on 2025-12-30 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('quantity', models.CharField(help_text='e.g. 2 kg, 1 packet', max_length=50)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('category', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='MealHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('date_cooked', models.DateField(auto_now_add=True)),
                ('ingredients_used', models.TextField(blank=True, help_text='List of ingredients used')),
            ],
            options={
                'verbose_name_plural': 'Meal Histories',
            },
        ),
    ]
